name: 'Deploy to S3 using Docker'
description: 'Deploys a folder to an S3 bucket using a Docker container'
inputs:
  bucket:
    description: 'The name of the S3 bucket to deploy to'
    required: true
  region:
    description: 'The AWS region of the S3 bucket'
    required: true
  dist-folder:
    description: 'The folder containing the files to deploy'
    required: true
outputs:
  deployed-url:
    description: 'The URL of the deployed application'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bucket }}
    - ${{ inputs.region }}
    - ${{ inputs.dist-folder }}