name: 'Get and Cache Dependencies'
description: 'Action to get and cache project dependencies'
inputs:
  caching:
    description: 'Whether to cache dependencies'
    required: false
    default: 'true'
  node-version:
    description: 'Version of NodeJS to use'
    required: true
runs:
  using: 'composite'
  steps:
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: inputs.node-version

      - name: Cache dependencies
        if: inputs.caching == 'true'
        id: cache-dependencies
        uses: actions/cache@v5
        with:
          path: ./app/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true' || inputs.caching != 'true'
        run: cd app && npm ci
        shell: bash